# workflow name
name: Hexo Blog CI

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: 检查master分支
        uses: actions/checkout@master
        
      - name: 7. 部署页面
        run: |
          cd ./public
          ls
          git init
          git config --global user.name 'Bigdogdou' 
          git config --global user.email '107261216@qq.com'
          git add .
          git commit -m "UpdateBigDogDou"
          git push --force --all https://${{ secrets.CODING_TOKEN }}@${{ secrets.CODING_REPO }}
